import { useLanguage } from '../contexts/LanguageContext';

const useMenuItems = () => {
  const { t } = useLanguage();

  const menuItems = [
    {
      id: 1,
      name: t('menuItem1'),
      price: 9.99,
      description: t('menuDesc1'),
      image: '/assets/menu-1-vegan-tacos.jpg',
      longDescription: t('menuLD1'),
      ingredients: t('menuIngredients1'),
      nutritionalInfo: t('menuNutrition1'),
      allergens: t('menuAllergens1'),
      category: 'l',
    },
    {
      id: 2,
      name: t('menuItem2'),
      price: 10.99,
      description: t('menuDesc2'),
      image: '/assets/menu-2-vegan-burrito.jpg',
      longDescription: t('menuLD2'),
      ingredients: t('menuIngredients2'),
      nutritionalInfo: t('menuNutrition2'),
      allergens: t('menuAllergens2'),
      category: 'l',
    },
    {
      id: 3,
      name: t('menuItem3'),
      price: 8.49,
      description: t('menuDesc3'),
      image: '/assets/menu-3-vegan-salad.jpg',
      longDescription: t('menuLD3'),
      ingredients: t('menuIngredients3'),
      nutritionalInfo: t('menuNutrition3'),
      allergens: t('menuAllergens3'),
      category: 'l',
    },
    {
      id: 4,
      name: t('menuItem4'),
      price: 11.49,
      description: t('menuDesc4'),
      image: '/assets/menu-4-vegan-burger.jpg',
      longDescription: t('menuLD4'),
      ingredients: t('menuIngredients4'),
      nutritionalInfo: t('menuNutrition4'),
      allergens: t('menuAllergens4'),
      category: 'l',
    },
    {
      id: 5,
      name: t('menuItem5'),
      price: 12.99,
      description: t('menuDesc5'),
      image: '/assets/menu-5-vegan-pizza.jpg',
      longDescription: t('menuLD5'),
      ingredients: t('menuIngredients5'),
      nutritionalInfo: t('menuNutrition5'),
      allergens: t('menuAllergens5'),
      category: 'd',
    },
    {
      id: 6,
      name: t('menuItem6'),
      price: 9.99,
      description: t('menuDesc6'),
      image: '/assets/menu-6-vegetarian-mc.jpg',
      longDescription: t('menuLD6'),
      ingredients: t('menuIngredients6'),
      nutritionalInfo: t('menuNutrition6'),
      allergens: t('menuAllergens6'),
      category: 'd',
    },
    {
      id: 7,
      name: t('menuItem7'),
      price: 13.49,
      description: t('menuDesc7'),
      image: '/assets/menu-7-vegetarian-lasagna.jpg',
      longDescription: t('menuLD7'),
      ingredients: t('menuIngredients7'),
      nutritionalInfo: t('menuNutrition7'),
      allergens: t('menuAllergens7'),
      category: 'd',
    },
    {
      id: 8,
      name: t('menuItem8'),
      price: 10.99,
      description: t('menuDesc8'),
      image: '/assets/menu-8-vegan-curry.jpg',
      longDescription: t('menuLD8'),
      ingredients: t('menuIngredients8'),
      nutritionalInfo: t('menuNutrition8'),
      allergens: t('menuAllergens8'),
      category: 'd',
    },
    {
      id: 9,
      name: t('menuItem9'),
      price: 11.99,
      description: t('menuDesc9'),
      image: '/assets/menu-9-vegan-bbowl.jpg',
      longDescription: t('menuLD9'),
      ingredients: t('menuIngredients9'),
      nutritionalInfo: t('menuNutrition9'),
      allergens: t('menuAllergens9'),
      category: 'l',
    },
    {
      id: 10,
      name: t('menuItem10'),
      price: 8.99,
      description: t('menuDesc10'),
      image: '/assets/menu-10-vegan-kabob.jpg',
      longDescription: t('menuLD10'),
      ingredients: t('menuIngredients10'),
      nutritionalInfo: t('menuNutrition10'),
      allergens: t('menuAllergens10'),
      category: 'l',
    },
    {
      id: 11,
      name: t('menuItem11'),
      price: 9.49,
      description: t('menuDesc11'),
      image: '/assets/menu-11-vegan-stirfry.jpg',
      longDescription: t('menuLD11'),
      ingredients: t('menuIngredients11'),
      nutritionalInfo: t('menuNutrition11'),
      allergens: t('menuAllergens11'),
      category: 'd',
    },
    {
      id: 12,
      name: t('menuItem12'),
      price: 8.99,
      description: t('menuDesc12'),
      image: '/assets/menu-12-vegan-sushi.jpg',
      longDescription: t('menuLD12'),
      ingredients: t('menuIngredients12'),
      nutritionalInfo: t('menuNutrition12'),
      allergens: t('menuAllergens12'),
      category: 'l',
    },
    {
      id: 13,
      name: t('menuItem13'),
      price: 10.49,
      description: t('menuDesc13'),
      image: '/assets/Vegan-staco.jpg',
      longDescription: t('menuLD13'),
      ingredients: t('menuIngredients13'),
      nutritionalInfo: t('menuNutrition13'),
      allergens: t('menuAllergens13'),
      category: 'l',
    },
    {
      id: 14,
      name: t('menuItem14'),
      price: 9.49,
      description: t('menuDesc14'),
      image: '/assets/Vegan-quesadillas.jpg',
      longDescription: t('menuLD14'),
      ingredients: t('menuIngredients14'),
      nutritionalInfo: t('menuNutrition14'),
      allergens: t('menuAllergens14'),
      category: 'l',
    },
    {
      id: 15,
      name: t('menuItem15'),
      price: 7.99,
      description: t('menuDesc15'),
      image: '/assets/Vegan-soup.jpg',
      longDescription: t('menuLD15'),
      ingredients: t('menuIngredients15'),
      nutritionalInfo: t('menuNutrition15'),
      allergens: t('menuAllergens15'),
      category: 'l',
    },
    {
      id: 16,
      name: t('menuItem16'),
      price: 10.99,
      description: t('menuDesc16'),
      image: '/assets/Vegan-masala.jpg',
      longDescription: t('menuLD16'),
      ingredients: t('menuIngredients16'),
      nutritionalInfo: t('menuNutrition16'),
      allergens: t('menuAllergens16'),
      category: 'l',
    },
    {
      id: 17,
      name: t('menuItem17'),
      price: 9.99,
      description: t('menuDesc17'),
      image: '/assets/vegan-quinoa.jpg',
      longDescription: t('menuLD17'),
      ingredients: t('menuIngredients17'),
      nutritionalInfo: t('menuNutrition17'),
      allergens: t('menuAllergens17'),
      category: 'l',
    },
    {
      id: 18,
      name: t('menuItem18'),
      price: 10.49,
      description: t('menuDesc18'),
      image: '/assets/vegan-sandwich.jpg',
      longDescription: t('menuLD18'),
      ingredients: t('menuIngredients18'),
      nutritionalInfo: t('menuNutrition18'),
      allergens: t('menuAllergens18'),
      category: 'l',
    },
    {
      id: 19,
      name: t('menuItem19'),
      price: 10.99,
      description: t('menuDesc19'),
      image: '/assets/vegan-quesadilla2.webp',
      longDescription: t('menuLD19'),
      ingredients: t('menuIngredients19'),
      nutritionalInfo: t('menuNutrition19'),
      allergens: t('menuAllergens19'),
      category: 'l',
    },
    {
      id: 20,
      name: t('menuItem20'),
      price: 11.49,
      description: t('menuDesc20'),
      image: '/assets/vegan-chili.avif',
      longDescription: t('menuLD20'),
      ingredients: t('menuIngredients20'),
      nutritionalInfo: t('menuNutrition20'),
      allergens: t('menuAllergens20'),
      category: 'd',
    },
    {
      id: 21,
      name: t('menuItem21'),
      price: 8.99,
      description: t('menuDesc21'),
      image: '/assets/vegan-tofu.jpg',
      longDescription: t('menuLD21'),
      ingredients: t('menuIngredients21'),
      nutritionalInfo: t('menuNutrition21'),
      allergens: t('menuAllergens21'),
      category: 'b',
    },
    {
      id: 22,
      name: t('menuItem22'),
      price: 11.99,
      description: t('menuDesc22'),
      image: '/assets/vegan-pepper.webp',
      longDescription: t('menuLD22'),
      ingredients: t('menuIngredients22'),
      nutritionalInfo: t('menuNutrition22'),
      allergens: t('menuAllergens22'),
      category: 'd',
    },
    {
      id: 23,
      name: t('menuItem23'),
      price: 12.49,
      description: t('menuDesc23'),
      image: '/assets/vegan-lentil.jpg',
      longDescription: t('menuLD23'),
      ingredients: t('menuIngredients23'),
      nutritionalInfo: t('menuNutrition23'),
      allergens: t('menuAllergens23'),
      category: 'd',
    },
    {
      id: 24,
      name: t('menuItem24'),
      price: 12.99,
      description: t('menuDesc24'),
      image: '/assets/vegan-banana.jpeg',
      longDescription: t('menuLD24'),
      ingredients: t('menuIngredients24'),
      nutritionalInfo: t('menuNutrition24'),
      allergens: t('menuAllergens24'),
      category: 'b',
    },
    {
      id: 25,
      name: t('menuItem25'),
      price: 8.99,
      description: t('menuDesc25'),
      image: '/assets/vegan-oats.webp',
      longDescription: t('menuLD25'),
      ingredients: t('menuIngredients25'),
      nutritionalInfo: t('menuNutrition25'),
      allergens: t('menuAllergens25'),
      category: 'b',
    },
    {
      id: 26,
      name: t('menuItem26'),
      price: 9.49,
      description: t('menuDesc26'),
      image: '/assets/vegan-wrap.webp',
      longDescription: t('menuLD26'),
      ingredients: t('menuIngredients26'),
      nutritionalInfo: t('menuNutrition26'),
      allergens: t('menuAllergens26'),
      category: 'b',
    },
    {
      id: 27,
      name: t('menuItem27'),
      price: 10.99,
      description: t('menuDesc27'),
      image: '/assets/vegan-pancake.webp',
      longDescription: t('menuLD27'),
      ingredients: t('menuIngredients27'),
      nutritionalInfo: t('menuNutrition27'),
      allergens: t('menuAllergens27'),
      category: 'b',
    },
    {
      id: 28,
      name: t('menuItem28'),
      price: 7.99,
      description: t('menuDesc28'),
      image: '/assets/citrus-smoothie.jpg',
      longDescription: t('menuLD28'),
      ingredients: t('menuIngredients28'),
      nutritionalInfo: t('menuNutrition28'),
      allergens: t('menuAllergens28'),
      category: 'o',
    },
    {
      id: 29,
      name: t('menuItem29'),
      price: 8.49,
      description: t('menuDesc29'),
      image: '/assets/avocado-latte.jpg',
      longDescription: t('menuLD29'),
      ingredients: t('menuIngredients29'),
      nutritionalInfo: t('menuNutrition29'),
      allergens: t('menuAllergens29'),
      category: 'o',
    },
    {
      id: 30,
      name: t('menuItem30'),
      price: 6.99,
      description: t('menuDesc30'),
      image: '/assets/berry-lemonade.jpg',
      longDescription: t('menuLD30'),
      ingredients: t('menuIngredients30'),
      nutritionalInfo: t('menuNutrition30'),
      allergens: t('menuAllergens30'),
      category: 'o',
    },    
  ];

  return menuItems;
};

export default useMenuItems;
